# 定义本 Validator 支持的验证类型
validator.type = v1

# 验证类型在网页中的显示名称
validator.typeLabel.v1 = Building Energy Metadata Profile v1.0

# v1 使用的固定 SHACL 规则
validator.shaclFile.v1 = shapes/building-energy-shapes_D.ttl

# 网页标题
validator.uploadTitle = Building Energy Metadata Validator

# 开启网页、REST API 和 SOAP API
validator.channels = form, rest_api, soap_api

# 默认报告格式
validator.defaultReportSyntax = application/ld+json